language: node_js
node_js:
  - 10
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@6.9.0
script:
  - npm run build
  - npm test
notifications:
  email:
    - tmikeschutte@gmail.com
