language: node_js
node_js:
  - 8
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@5.0.3
script:
  - npm run build
  - npm test
notifications:
  email:
    - tmikeschutte@gmail.com
